### ISSUE TITLE
When 3553 can support windows10 X 64？

### ISSUE THREAD

**Issue by huanx9** [kxproject/kX-Audio-driver-binaries#5]

**Comment by flood404** [comment]
I just installed it on Windows 10 x64 and it works.  Just if you enabled secure boot or use secure boot in BIOS it will not load an unsigned driver for KX project.

**Comment by dusttea** [comment]
It works for the first time on Windows 10 64bit and the computer crashes with a beep sound.
It is not a driver problem.

**Comment by moonman** [comment]
It works with Windows 10 x64 just fine. I have Audigy 2 with PCIe to PCI adapter on AMD x570 (brand new) motherboard. Everything functions as it should. Something else is going on with your PC. This can be closed.
